# Generated by Django 4.2.2 on 2023-06-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoFacturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_recepcion', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.estadofacturas')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.estadoproducto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.facturas')),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(max_length=50)),
                ('stock_min_tienda', models.IntegerField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.bodegas')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tiendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.productos')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.productos')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.tiendas'),
        ),
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.ingresoproductos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.productos')),
            ],
        ),
        migrations.AddField(
            model_name='marcas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.proveedores'),
        ),
        migrations.AddField(
            model_name='ingresoproductos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.productos'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.proveedores'),
        ),
    ]
