# Generated by Django 4.2.2 on 2023-06-16 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingresoproductos',
            old_name='estado_producto',
            new_name='estado',
        ),
    ]
