# Generated by Django 4.2.2 on 2023-06-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_rename_estado_producto_ingresoproductos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_csv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_barras', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
