# Generated by Django 4.2.2 on 2023-06-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_alter_import_csv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import_csv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
