# Generated by Django 4.2.2 on 2023-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0005_alter_import_csv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproductos',
            name='precio_compra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ingresoproductos',
            name='precio_venta',
            field=models.IntegerField(),
        ),
    ]
