# Generated by Django 4.2.2 on 2023-06-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0006_alter_ingresoproductos_precio_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproductos',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
