# Generated by Django 4.2.2 on 2023-11-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0007_stockproductos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproductos',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
